### ISSUE TITLE
[BUG] Attempting to upload fonts results in Bad Request

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#565]
**Describe the Issue**
Attempting to upload any fonts to Sheezy with a Pro+ Subscription results in a Bad Request popup (pictured in Screenshots section)

**To Reproduce**
Prerequisites:
- Active Pro subscription or higher
OR
- Helper role or higher

Steps to reproduce the behaviour:
- Edit your profile
- Attempt to upload a font
- Click Upload
- Popup telling me to refresh the page due to bad request

**Expected Behaviour**
The font would successfully upload.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/3385b046-10dd-4956-b9d8-604ef39bf40b)
*The popup*

**Device**
- Type: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 127.0.2 (64-bit)

**Comment by betalambda** [comment]
To add, the font I am attempting to upload is a .ttf file, which the site says it supports, yet I am getting the following error:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/5e7fd18a-ce6c-4e70-87f2-b090188af3be)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/d5622437-fe44-48f2-950d-a3a21335fc9e)
*proof the site tells me it accepts .ttf files*

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/4b8589a1-d4ce-43e6-b45c-3e0da6c7445e)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/8ddfced5-be40-4975-b3bd-975ea9869580)
*both nunito and coolvectia here are .ttf files*

**Comment by xnyoom** [comment]
Caused by [2024-07-01](https://github.com/Sheezy-Art/sheezy-hub/releases/tag/2024-07-01)

**Comment by boylett** [comment]
Hm. I am able to upload TTF files no problem. Could you attach the font files here, or perhaps via a [FileGarden](https://filegarden.com) link so that I can inspect them?

**Comment by xnyoom** [comment]
I can reproduce it with [Roboto](https://fonts.google.com/specimen/Roboto)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/122828f5-1f38-401b-ba6b-0d1d8b18b302)

## Firefox 127.0.2
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/8ccc01f8-9a60-443a-8d4a-e5a47d913a02)

## Chrome 126.0.6478.127
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/da33e76a-2719-4496-a590-deb05a80d6d7)

**Comment by xnyoom** [comment]
On iOS Safari the values are as expected
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/340afb8d-af4e-42fb-98ef-2372a86fb2a2)

**Comment by boylett** [comment]
Ah. Seems to be a browser issue - some browsers fail to correctly report the mimetype of font files. Will look into this

**Comment by boylett** [comment]
Fixed by [#97e1643](https://github.com/Sheezy-Art/sheezy.art/commit/97e16432526ecaaac92286d1b05e1000b278b662)

**Comment by xnyoom** [comment]
Not fixed.
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/7f580c0a-cc6b-4ae7-a65e-375d90c2b5b2)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/d64b7b64-c161-4f65-9859-cdbefd0d7049)

**Comment by xnyoom** [comment]
Should be fixed now. Let us know if it isn't. https://github.com/Sheezy-Art/sheezy-hub/issues/566#issuecomment-2212069026
