### ISSUE TITLE
[BUG] Flash File (SWF) not uploading in a 400 Bad Request

### ISSUE THREAD

**Issue by Lynkronized** [Sheezy-Art/sheezy-hub#566]
**Describe the Issue**
Heya, been tryin' to upload my flash file (swf), but it keeps getting a "400 Bad Request" every time i upload a flash file, i dunno if it's a bug or something but it wouldn't let me upload flash files, maybe you could probably fix this, maybe???

**To Reproduce**
1. Go to 'Upload Artwork'
2. Click on 'Upload'
3. Browse a Flash File (SWF) and open a file or drag it on to an Upload icon
4. Popping up a 400 Bad Request

**Expected Behaviour**
a Flash file (SWF) should upload properly

**Screenshots**
![Mqtw3mmSA5](https://github.com/Sheezy-Art/sheezy-hub/assets/174840426/5f07bda7-1561-494d-a879-fe360b1cf622)
![DoiIdsoJ5z](https://github.com/Sheezy-Art/sheezy-hub/assets/174840426/7e6c360c-171b-4c71-984f-03b5504856d3)

**Device**
- Type: Desktop
- OS: Windows 11
- Browser: Firefox
- Version: 127.0.2 (64-bit)

**Comment by betalambda** [comment]
I think I had a similar issue with fonts in #565

**Comment by xnyoom** [comment]
Firefox doesn't detect the MIME. Chrome and Safari identify it correctly but fail anyway because `application/x-shockwave-flash` isn't allowed server-side.

## Firefox
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/1e4853a1-9dc3-44a6-84cd-e1b3b446d3ef)

## Chrome
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/5b3a7c39-e900-413f-8b0f-d7d4f45e8fb8)

## Safari
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/fb856b11-3dcf-43d4-abfc-9f0fd66af223)

**Comment by boylett** [comment]
Fixed by [#97e1643](https://github.com/Sheezy-Art/sheezy.art/commit/97e16432526ecaaac92286d1b05e1000b278b662)

**Comment by xnyoom** [comment]
Not fixed. Now `filetype` is set to `swf` instead of an empty string but the error is the same.
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/183fa8cc-f803-460a-8a3d-0638461c3c1e)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/53cad4af-5d25-40c6-aacc-59b4358c7b09)

**Comment by boylett** [comment]
Could you please re-test this following the latest bugfix? It seems none of the systems I have available to me can replicate this issue.

**Comment by boylett** [comment]
Yippee!!
